### ISSUE TITLE
update serverless@2 to serverless@3

### ISSUE THREAD

**Issue by Trott** [ucsf-ckm/zorgbort#125]
Update serverless@2 to serverless@3.

https://www.serverless.com/framework/docs/guides/upgrading-v3

You will want to update serverless-offline to 8.4.0 to avoid peer dependency issues. I'll open that PR right now.

**Comment by Trott** [comment]
The update guide above says that the first thing to do is to update to the latest 2.x, which we did this morning, and then to run your serverless commands and see if there are any deprecation warnings. Is that second part something someone can do? @stopfstedt @jrjohnson

**Comment by jrjohnson** [comment]
It runs a deploy on merge at https://github.com/ucsf-ckm/zorgbort/actions/runs/1791642566 so you can see it there.

**Comment by Trott** [comment]
> It runs a deploy on merge at https://github.com/ucsf-ckm/zorgbort/actions/runs/1791642566 so you can see it there.

Great. There are no deprecations in the logs for that action run. Our only plugin has also been updated to a serverless@3-compatible version. So we're most of the way there...
